import * as THREE from 'three';
import './style.css';

const app=document.querySelector<HTMLDivElement>('#app')!;
app.innerHTML=`<div class="noise"></div><div class="vignette"></div><div class="hud"><div class="topbar"><div class="mission"><div class="eyebrow">Operation Nightfall</div><div class="objective">Secure the relay station</div></div><div class="squad"><i></i><i></i><i></i><i></i></div></div><div class="compass">NW 330 <b>N&nbsp; 015</b> NE 060</div><div class="crosshair"></div><div class="hitmarker"></div><div class="health"><div class="health-label"><span>Combat integrity</span><span id="hp">100</span></div><div class="health-bar"><span></span></div></div><div class="ammo"><div class="ammo-main"><span id="rounds">30</span> <small>/ 120</small></div><div class="weapon-name">VX-7 // 5.56 Tactical</div></div><div class="status">LMB fire · R reload · Shift sprint · WASD move</div></div><div class="damage"></div><div class="muzzle"></div><div class="menu"><div class="panel"><div class="logo">NIGHTFALL // PROTOCOL</div><div class="title">BLACK<br><span>OUTPOST</span></div><p class="brief">02:17 UTC — A hostile signal has gone live beneath the Svalbard relay. Infiltrate the perimeter. Neutralize the autonomous defense grid. Leave no trace.</p><button class="start">Deploy mission</button><div class="controls">WASD MOVE · MOUSE AIM · CLICK FIRE · SHIFT SPRINT · R RELOAD</div></div></div><div class="mobile"><div class="stick"></div><button class="fire">FIRE</button></div>`;

const scene=new THREE.Scene(); scene.background=new THREE.Color(0x04090b); scene.fog=new THREE.FogExp2(0x071114,.025);
const camera=new THREE.PerspectiveCamera(72,innerWidth/innerHeight,.08,180); camera.position.set(0,1.7,11);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'}); renderer.setSize(innerWidth,innerHeight); renderer.setPixelRatio(Math.min(devicePixelRatio,1.8)); renderer.outputColorSpace=THREE.SRGBColorSpace; renderer.shadowMap.enabled=true; renderer.shadowMap.type=THREE.PCFSoftShadowMap; renderer.toneMapping=THREE.ACESFilmicToneMapping; renderer.toneMappingExposure=.88; app.prepend(renderer.domElement);

const hemi=new THREE.HemisphereLight(0x7299a7,0x06100d,.52); scene.add(hemi);
const moon=new THREE.DirectionalLight(0xa9cfdd,2.4); moon.position.set(-15,24,-12); moon.castShadow=true; moon.shadow.mapSize.set(2048,2048); moon.shadow.camera.left=-35;moon.shadow.camera.right=35;moon.shadow.camera.top=35;moon.shadow.camera.bottom=-35;scene.add(moon);
const amber=new THREE.PointLight(0xffa52d,18,18,2);amber.position.set(0,4,-17);scene.add(amber);

function mat(color:number,rough=.7,metal=.1){return new THREE.MeshStandardMaterial({color,roughness:rough,metalness:metal})}
const ground=new THREE.Mesh(new THREE.PlaneGeometry(140,140,50,50),mat(0x19201e,.95,.05));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);
// snow/ash ground variation
const pos=ground.geometry.attributes.position; for(let i=0;i<pos.count;i++)pos.setZ(i,(Math.sin(pos.getX(i)*.37)+Math.cos(pos.getY(i)*.29))*.09);
const road=new THREE.Mesh(new THREE.PlaneGeometry(8,110),mat(0x111716,.95));road.rotation.x=-Math.PI/2;road.position.y=.025;road.position.z=-28;scene.add(road);
for(let z=-75;z<25;z+=6){const dash=new THREE.Mesh(new THREE.PlaneGeometry(.08,2),new THREE.MeshBasicMaterial({color:0xb9a568}));dash.rotation.x=-Math.PI/2;dash.position.set(0,.04,z);scene.add(dash)}

// brutalist relay compound
const concrete=mat(0x26302e,.82,.05), dark=mat(0x0c1314,.4,.65), steel=mat(0x273332,.28,.8);
function box(x:number,y:number,z:number,sx:number,sy:number,sz:number,m:THREE.Material=concrete){const o=new THREE.Mesh(new THREE.BoxGeometry(sx,sy,sz),m);o.position.set(x,y,z);o.castShadow=o.receiveShadow=true;scene.add(o);return o}
box(0,3,-24,20,6,12);box(-7,7,-24,5,3,11,dark);box(7,6,-24,4,6,10,dark);box(0,6.15,-24,19,.18,11,steel);
for(const x of [-8,-4,0,4,8]){const slit=box(x,3.4,-17.92,1.8,.16,.08,new THREE.MeshBasicMaterial({color:0xffb33e}));slit.position.z=-17.91}
const door=box(0,1.6,-17.85,3.3,3.2,.2,dark); for(const x of [-1.25,1.25])box(x,1.7,-17.7,.1,2.7,.12,new THREE.MeshBasicMaterial({color:0x50d5bd}));
for(const side of [-1,1])for(let z=-5;z>-55;z-=10){box(side*8.5,1.25,z,1.2,2.5,4,concrete);box(side*7.85,2.1,z,.1,.2,3,new THREE.MeshBasicMaterial({color:0xe9b94e}));}
// antenna tower
const tower=new THREE.Group();scene.add(tower);tower.position.set(-9,9,-27);for(let y=0;y<18;y+=2){const ring=new THREE.Mesh(new THREE.TorusGeometry(1.4,.07,8,4),steel);ring.rotation.x=Math.PI/2;ring.position.y=y;tower.add(ring)}for(let a=0;a<4;a++){const beam=new THREE.Mesh(new THREE.CylinderGeometry(.08,.08,18,6),steel);beam.position.set(Math.cos(a*Math.PI/2)*1.35,9,Math.sin(a*Math.PI/2)*1.35);tower.add(beam)}const beacon=new THREE.PointLight(0xff2515,30,30,2);beacon.position.set(-9,28,-27);scene.add(beacon);const beaconMesh=new THREE.Mesh(new THREE.SphereGeometry(.22),new THREE.MeshBasicMaterial({color:0xff301c}));beaconMesh.position.copy(beacon.position);scene.add(beaconMesh);
// mountains
for(let i=0;i<26;i++){const h=8+Math.random()*22,r=5+Math.random()*8;const mountain=new THREE.Mesh(new THREE.ConeGeometry(r,h,5),mat(0x182322,.98));const a=(i/26)*Math.PI*2,dist=48+Math.random()*28;mountain.position.set(Math.cos(a)*dist,h/2-1,Math.sin(a)*dist-18);mountain.rotation.y=Math.random()*Math.PI;scene.add(mountain)}
// floodlights
for(const x of [-10,10]){box(x,2.5,-10,.2,5,.2,steel);const l=new THREE.SpotLight(0x9ee8ff,35,35,.5,.5,1);l.position.set(x,5,-10);l.target.position.set(x*.35,0,-22);l.castShadow=true;scene.add(l,l.target);box(x,5,-10,1,.4,.5,dark)}

// drifting snow particles
const snowGeo=new THREE.BufferGeometry(),snowCount=1700,snowArr=new Float32Array(snowCount*3);for(let i=0;i<snowCount;i++){snowArr[i*3]=(Math.random()-.5)*90;snowArr[i*3+1]=Math.random()*28;snowArr[i*3+2]=(Math.random()-.5)*100-20}snowGeo.setAttribute('position',new THREE.BufferAttribute(snowArr,3));const snow=new THREE.Points(snowGeo,new THREE.PointsMaterial({color:0xc9e4e8,size:.055,transparent:true,opacity:.55,depthWrite:false}));scene.add(snow);

// targets
const targets:THREE.Mesh[]=[];function spawnTarget(x:number,z:number){const g=new THREE.Group();g.position.set(x,1.55,z);scene.add(g);const body=new THREE.Mesh(new THREE.CapsuleGeometry(.38,.95,5,10),mat(0x252e2d,.45,.7));body.castShadow=true;g.add(body);const visor=new THREE.Mesh(new THREE.BoxGeometry(.52,.16,.35),new THREE.MeshBasicMaterial({color:0xf04421}));visor.position.set(0,.62,.27);g.add(visor);const hit=new THREE.Mesh(new THREE.SphereGeometry(.6),new THREE.MeshBasicMaterial({visible:false}));hit.userData.group=g;hit.userData.hp=3;g.add(hit);targets.push(hit)}
[[-4,-8],[5,-14],[-6,-29],[5,-36],[0,-46]].forEach(([x,z])=>spawnTarget(x,z));

// weapon viewmodel
const weapon=new THREE.Group();camera.add(weapon);scene.add(camera);weapon.position.set(.42,-.42,-.72);weapon.rotation.set(-.04,-.04,0);const gun=mat(0x111817,.25,.9),grip=mat(0x232a27,.75,.1);const receiver=new THREE.Mesh(new THREE.BoxGeometry(.25,.24,.85),gun);receiver.position.z=-.25;weapon.add(receiver);const barrel=new THREE.Mesh(new THREE.CylinderGeometry(.045,.055,.75,10),gun);barrel.rotation.x=Math.PI/2;barrel.position.set(0,.04,-.9);weapon.add(barrel);const handguard=new THREE.Mesh(new THREE.BoxGeometry(.22,.2,.55),grip);handguard.position.z=-.62;weapon.add(handguard);const sight=new THREE.Mesh(new THREE.BoxGeometry(.13,.13,.2),dark);sight.position.set(0,.18,-.24);weapon.add(sight);const screen=new THREE.Mesh(new THREE.PlaneGeometry(.09,.06),new THREE.MeshBasicMaterial({color:0x4af0c6}));screen.position.set(.126,.03,-.24);screen.rotation.y=Math.PI/2;weapon.add(screen);

const keys=new Set<string>();let yaw=0,pitch=0,started=false,ammo=30,reloading=false,bob=0,recoil=0;
addEventListener('keydown',e=>{keys.add(e.code);if(e.code==='KeyR')reload()});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('mousemove',e=>{if(document.pointerLockElement===renderer.domElement){yaw-=e.movementX*.0017;pitch=Math.max(-1.25,Math.min(1.2,pitch-e.movementY*.0017))}});
document.querySelector('.start')!.addEventListener('click',()=>{started=true;document.querySelector('.menu')!.classList.add('hidden');renderer.domElement.requestPointerLock()});renderer.domElement.addEventListener('click',()=>{if(started){if(document.pointerLockElement!==renderer.domElement)renderer.domElement.requestPointerLock();else shoot()}});document.querySelector('.fire')?.addEventListener('pointerdown',shoot);
function reload(){if(reloading||ammo===30)return;reloading=true;(document.querySelector('.status') as HTMLElement).textContent='RELOADING';weapon.rotation.z=.7;setTimeout(()=>{ammo=30;reloading=false;weapon.rotation.z=0;updateAmmo();(document.querySelector('.status') as HTMLElement).textContent='LMB fire · R reload · Shift sprint · WASD move'},1250)}function updateAmmo(){document.querySelector('#rounds')!.textContent=String(ammo)}
const ray=new THREE.Raycaster();function shoot(){if(!started||reloading)return;if(ammo<=0){reload();return}ammo--;updateAmmo();recoil=.09;document.querySelector('.muzzle')!.classList.add('on');setTimeout(()=>document.querySelector('.muzzle')!.classList.remove('on'),45);ray.setFromCamera(new THREE.Vector2(),camera);const hits=ray.intersectObjects(targets,false);if(hits[0]){const t=hits[0].object as THREE.Mesh;t.userData.hp--;document.querySelector('.hitmarker')!.classList.add('on');setTimeout(()=>document.querySelector('.hitmarker')!.classList.remove('on'),90);if(t.userData.hp<=0){const g=t.userData.group as THREE.Group;targets.splice(targets.indexOf(t),1);g.rotation.z=1.3;g.position.y=-.2;setTimeout(()=>scene.remove(g),800)}}}

const clock=new THREE.Clock(),velocity=new THREE.Vector3();function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.04),time=clock.elapsedTime;camera.rotation.order='YXZ';camera.rotation.y=yaw;camera.rotation.x=pitch-recoil;recoil*=Math.pow(.001,dt);if(started){const forward=Number(keys.has('KeyW'))-Number(keys.has('KeyS')),side=Number(keys.has('KeyD'))-Number(keys.has('KeyA')),sprint=keys.has('ShiftLeft')?8.5:4.8;const move=new THREE.Vector3(side,0,-forward).normalize().applyAxisAngle(new THREE.Vector3(0,1,0),yaw);velocity.lerp(move.multiplyScalar(sprint),1-Math.pow(.001,dt));camera.position.addScaledVector(velocity,dt);camera.position.x=Math.max(-7.2,Math.min(7.2,camera.position.x));camera.position.z=Math.max(-50,Math.min(14,camera.position.z));bob+=velocity.length()*dt;camera.position.y=1.7+Math.sin(bob*2.2)*.035;weapon.position.y=-.42+Math.sin(bob*2.2)*.012;weapon.position.x=.42+Math.cos(bob*1.1)*.009}const arr=snowGeo.attributes.position.array as Float32Array;for(let i=0;i<snowCount;i++){arr[i*3+1]-=dt*(1.2+(i%7)*.1);arr[i*3]+=.25*dt;if(arr[i*3+1]<0)arr[i*3+1]=28}snowGeo.attributes.position.needsUpdate=true;beacon.intensity=18+Math.sin(time*3)*12;targets.forEach((t,i)=>{const g=t.userData.group as THREE.Group;g.position.y=1.55+Math.sin(time*1.7+i)*.025});renderer.render(scene,camera)}animate();
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
